<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAQdkHue\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAQdkHue/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerAQdkHue.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerAQdkHue\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerAQdkHue\appAppKernelProdContainer([
    'container.build_hash' => 'AQdkHue',
    'container.build_id' => '41754fed',
    'container.build_time' => 1708988533,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAQdkHue');
