<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4mcv2tX\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4mcv2tX/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container4mcv2tX.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container4mcv2tX\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container4mcv2tX\appAppKernelProdContainer([
    'container.build_hash' => '4mcv2tX',
    'container.build_id' => 'c0a41029',
    'container.build_time' => 1708988319,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4mcv2tX');
